### PR TITLE
change assert on timeout duration to max(timeout, min_time)

### PR DESCRIPTION
**Pull request by ClintLiddick**
Should we leave the assert and build in Release mode @psigen @mkoval?

### CODE REVIEW

**Comment by mkoval** [comment]
What's the motivation for this change? It seems like the `max` would only activate in the case where the `assert` would trip.

**Comment by psigen** [comment]
The motivation is that having a timeout smaller than a microsecond is not actually an error when running non-realtime, and we see it in some of the code where this sleep is being used wait for a timeout.

We could also potentially sleep for `>= 0L`. The important change is not crashing the whole program just because a small sleep interval is requested.

This was the simplest change that preserved the logic of the comment that was in the existing code.  We didn't know if there was some specific reason they wanted this minimum time.

Note that [the boost function they are using is deprecated](http://www.boost.org/doc/libs/1_53_0/doc/html/thread/thread_management.html#thread.thread_management.this_thread.sleep) in favor of using `sleep_until()`, which wouldn't have this issue in the first place.

**Comment by ClintLiddick** [comment]
Right, the assert isn't actually a valid error state, and occurs occasionally at runtime.

**Comment by mkoval** [comment]
> The motivation is that having a timeout smaller than a microsecond is not actually an error when running non-realtime.

I agree, but I am trying to understand what motivated Barrett to add the assertion.Why is it an error to sleep for less than 1 us when running on a realtime OS? Does this have something to do with the time quantum used by the scheduler? What breaks if you violate this condition?

Or is this just an ill-fated attempt to catch schedule overruns?

> Note that the boost function they are using is deprecated in favor of using `sleep_until()`, which wouldn't have this issue in the first place.

It is deprecated in favor of `sleep_until()` **or** `sleep_for()`. The only difference between `sleep_for()` and `sleep()` is the type of `duration` object that it accepts. Sleeping for a duration is *not* deprecated, although I agree `sleep_until()` is often a superior semantic.

> Right, the assert isn't actually a valid error state, and occurs occasionally at runtime.

I am not comfortable declaring this *not* an error state unless we understand why the assertion was added in the first place. Any ideas?

**Comment by psigen** [comment]
> I agree, but I am trying to understand what motivated Barrett to add the assertion.Why is it an error to sleep for less than 1 us when running on a realtime OS? Does this have something to do with the time quantum used by the scheduler? What breaks if you violate this condition?

> I am not comfortable declaring this not an error state unless we understand why the assertion was added in the first place. Any ideas?

The obvious guess is that they designed this on a system where the clock they accessed was in microseconds, and were attempting to detect sleeps of `0` seconds, which indicated schedule overruns somewhere on an RT system.

As far as I can tell, there is nothing special about `1uS` that would matter to this code.

>It is deprecated in favor of sleep_until() or sleep_for(). The only difference between sleep_for() and sleep() is the type of duration object that it accepts. Sleeping for a duration is not deprecated, although I agree sleep_until() is often a superior semantic.

Kovalization: "Under the modern sleep API, `sleep_until()` would be the correct and easier way to implement this timeout, and this would not be an issue in the first place."

**Comment by mkoval** [comment]
> The obvious guess is that they designed this on a system where the clock they accessed was in microseconds, and were attempting to detect sleeps of 0 seconds, which indicated schedule overruns somewhere on an RT system.

A wrapper around `sleep()` is a terrible place to implement overrun detection logic. But I suspect that you are correct.

> Kovalization: "Under the modern sleep API, sleep_until() would be the correct and easier way to implement this timeout, and this would not be an issue in the first place."

No. It is misleading to say that this function is deprecated: `sleep_until()` and `sleep_for()` both have use cases. _In general_ I would prefer to use `sleep_until()` to implement a periodic loop with a fixed frequency, but I have not inspected the `libbarrett` closely enough to conclude whether or not that is the case here.

To be honest, I am a bit surprised that there is a sleep *at all* in `getProperty`. I'll have to dig into the implementation to see why that is the case.

**Comment by psigen** [comment]
>No. It is misleading to say that this function is deprecated

Yes. That is why I removed that statement from the Kovalization of the comment.

**Pull request closed without merging**
